import "@/styles/globals.css";
import "katex/dist/katex.min.css";

import {NextUIProvider} from "@nextui-org/react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
          {children}
        </NextUIProvider>
      </body>
    </html>
  )
}
